/**
 * Initial data taken from the supplied Just Cakes menu.
 * After seeding, the owner edits everything from the dashboard.
 */

export const categories = [
  { name: 'Cupcakes', description: 'Single-serve cupcakes baked fresh each morning.', displayOrder: 1 },
  { name: 'Cakes', description: 'Everyday celebration cakes in classic flavours.', displayOrder: 2 },
  { name: 'Premium Cakes', description: 'Richer recipes for the bigger occasions.', displayOrder: 3 },
  { name: 'Premium Creations', description: 'Small-batch cakes with a finer finish.', displayOrder: 4 },
  { name: 'Signature Cakes', description: 'The flavours Just Cakes is known for.', displayOrder: 5 },
];

export const products = [
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
  {
    name: 'Pineapple Cake',
    category: 'Signature Cakes',
    description: 'Soft vanilla sponge layered with pineapple crush and whipped cream.',
    flavours: ['Pineapple'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Chocolate Cake',
    category: 'Signature Cakes',
    description: 'Cocoa sponge with a smooth chocolate cream finish.',
    flavours: ['Chocolate'],
    pricing: [
      { label: '0.5 Kg', price: 400 },
      { label: '1 Kg', price: 800 },
    ],
    isFeatured: true,
  },
  {
    name: 'Strawberry Cake',
    category: 'Signature Cakes',
    description: 'Vanilla sponge with strawberry cream and fresh fruit on top.',
    flavours: ['Strawberry'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Rasmalai Cake',
    category: 'Signature Cakes',
    description: 'Cardamom-scented sponge soaked in rabri with pistachio and saffron.',
    flavours: ['Rasmalai'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
    isFeatured: true,
  },
  {
    name: 'Kiwi Cake',
    category: 'Signature Cakes',
    description: 'Light sponge with kiwi cream and fresh kiwi slices.',
    flavours: ['Kiwi'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Butterscotch Cake',
    category: 'Signature Cakes',
    description: 'Butterscotch cream and praline crunch between vanilla layers.',
    flavours: ['Butterscotch'],
    pricing: [
      { label: '0.5 Kg', price: 350 },
      { label: '1 Kg', price: 700 },
    ],
  },
  {
    name: 'Red Velvet Cake',
    category: 'Premium Creations',
    description: 'Classic red velvet with cream cheese frosting.',
    flavours: ['Red Velvet'],
    pricing: [{ label: '0.5 Kg', price: 350 }],
    isFeatured: true,
  },
  {
    name: 'Choco Truffle Cake',
    category: 'Premium Creations',
    description: 'Dark chocolate truffle ganache over a moist chocolate base.',
    flavours: ['Chocolate Truffle'],
    pricing: [{ label: '0.5 Kg', price: 450 }],
  },
  {
    name: 'Choco Lava Cake',
    category: 'Cupcakes',
    description: 'Warm chocolate cake with a molten centre. Sold per piece.',
    flavours: ['Chocolate'],
    pricing: [{ label: '1 Piece', price: 80 }],
  },
  {
    name: 'Muffin',
    category: 'Cupcakes',
    description: 'Everyday bakery muffin, baked fresh daily. Sold per piece.',
    flavours: ['Chocolate', 'Vanilla'],
    pricing: [{ label: '1 Piece', price: 60 }],
  },
];
